# Essa file é apenas para testar os requests com token usando a extensão "REST" do VSCode
# User faz login -> Token é gerado
# User faz logout -> Token é deletado

# Create User
POST http://127.0.0.1:8000/userSignin/
Content-Type: application/json

{
    "username": "Zanda Comp",
    "email": "gabriel.zanda@compjunior.com.br",
    "password": "123",
    "role": "Manager"
}

###

# Login User with Token
POST http://127.0.0.1:8000/userLogin/
Content-Type: application/json

{
    "email": "zandaManager@gmail.com",
    "password": "123"
}

###

# Test user token authentication
GET http://127.0.0.1:8000/userTest/
Content-Type: application/json
Authorization: Token 08be12f8eb94bcc1f3c4a3a608fc431f0ced82de

{}

###

# Logout user
GET http://127.0.0.1:8000/userLogout/
Content-Type: application/json
Authorization: Token 08be12f8eb94bcc1f3c4a3a608fc431f0ced82de

{}

### 

# Get all user Tasks
GET http://127.0.0.1:8000/allUserTasks/
Content-Type: application/json
Authorization: Token 08be12f8eb94bcc1f3c4a3a608fc431f0ced82de

{}

###

#Create task
POST http://127.0.0.1:8000/createTask/
Content-Type: application/json
Authorization: Token 08be12f8eb94bcc1f3c4a3a608fc431f0ced82de

{
    "description":"Fazer outro Trabalho",
    "status":"Pendente",
    "approval_status":"Não Avaliada",
    "responsible": 3
}