# Essa file é apenas para testar os requests com token usando a extensão "REST" do VSCode
# User faz login -> Token é gerado
# User faz logout -> Token é deletado

# Create User
POST http://127.0.0.1:8000/userSignin/
Content-Type: application/json

{
    "username": "Zanda5",
    "email": "zanda5@gmail.com",
    "password": "123",
    "role": "Manager"
}

###

# Login User with Token
POST http://127.0.0.1:8000/userLogin/
Content-Type: application/json

{
    "email": "zanda5@gmail.com",
    "password": "123"
}

###

# Test user token authentication
GET http://127.0.0.1:8000/userTest/
Content-Type: application/json
Authorization: Token fe8687af7445dfaae983f7de4da6a682fcf7f8f2

###

# Logout user
GET http://127.0.0.1:8000/userLogout/
Content-Type: application/json
Authorization: Token fe8687af7445dfaae983f7de4da6a682fcf7f8f2

### 

# Get All Tasks
GET http://127.0.0.1:8000/tasks/
Content-Type: application/json
Authorization: Token fe8687af7445dfaae983f7de4da6a682fcf7f8f2

###

# Get one Task by id
GET http://127.0.0.1:8000/tasks/2/
Content-Type: application/json
Authorization: Token fe8687af7445dfaae983f7de4da6a682fcf7f8f2

###

#Create task
POST http://127.0.0.1:8000/createTask/
Content-Type: application/json
Authorization: Token fe8687af7445dfaae983f7de4da6a682fcf7f8f2

{
    "description":"Fazer Trabalho",
    "status":"Pendente",
    "approval_status":"Não Avaliada",
    "responsible": 2
}

###

# Delete Task
DELETE http://127.0.0.1:8000/deleteTask/2/
Content-Type: application/json
Authorization: Token d11cdb5ee4ad592edd6e8e2c3781ac2beecbb562

###

# Get All Users
GET http://127.0.0.1:8000/users/
Content-Type: application/json
Authorization: Token d11cdb5ee4ad592edd6e8e2c3781ac2beecbb562

###

# Get one User by id
GET http://127.0.0.1:8000/users/1/
Content-Type: application/json
Authorization: Token d11cdb5ee4ad592edd6e8e2c3781ac2beecbb562

###

# Edit Task
PUT http://127.0.0.1:8000/editTask/2/
Content-Type: application/json
Authorization: Token fe8687af7445dfaae983f7de4da6a682fcf7f8f2

{
    "description":"Agora sim Alterada por Worker",
    "status":"Pendente",
    "approval_status":"Aprovada",
    "responsible": 2
}

###

# Delete User
DELETE  http://127.0.0.1:8000/deleteUser/1/
Content-Type: application/json
Authorization: Token d11cdb5ee4ad592edd6e8e2c3781ac2beecbb562