# Essa file é apenas para testar os requests com token usando a extensão "REST" do VSCode
# User faz login -> Token é gerado
# User faz logout -> Token é deletado

# Create User
POST http://127.0.0.1:8000/userSignin/
Content-Type: application/json

{
    "username": "Zanda3",
    "email": "zanda3@gmail.com",
    "password": "123",
    "role": "Worker"
}

###

# Login User with Token
POST http://127.0.0.1:8000/userLogin/
Content-Type: application/json

{
    "email": "zanda3@gmail.com",
    "password": "123"
}

###

# Test user token authentication
GET http://127.0.0.1:8000/userTest/
Content-Type: application/json
Authorization: Token f9cb5d432e62de9bb3e1ffd2076db5f2abf986c9

{}

###

# Logout user
GET http://127.0.0.1:8000/userLogout/
Content-Type: application/json
Authorization: Token f9cb5d432e62de9bb3e1ffd2076db5f2abf986c9

{}