# Generated by Django 4.2.4 on 2023-10-31 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Worker', 'Worker'), ('Manager', 'Manager')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pronta', 'Pronta')], max_length=10)),
                ('approval_status', models.CharField(choices=[('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada'), ('Não Avaliada', 'Não Avaliada')], max_length=15)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks_app.user')),
            ],
        ),
    ]
