# Generated by Django 4.2.4 on 2023-11-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='approval_status',
            field=models.CharField(choices=[('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada'), ('Não Avaliada', 'Não Avaliada')], default='Não Avaliada', max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pronta', 'Pronta')], default='Pendente', max_length=10),
        ),
    ]
