# Generated by Django 4.2.7 on 2023-11-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0011_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Worker', 'Worker'), ('Manager', 'Manager')], default='Worker', max_length=10),
        ),
    ]
