version: '3.1'

services:  
  database:
    image: postgres:13.1
    env_file:
      - config/postgres.env
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq
    env_file:
      - config/rabbitmq.env
    ports:
      - 5672:5672
  
  adminer:
    image: adminer
    ports:
      - 8080:8080

  consumer:
    build: 
      dockerfile: dockerfile.jobs
    restart: unless-stopped
    depends_on:
      - rabbitmq